theme: minima
title: Interplanetary Technology
author: Joseph Feruglio
email: 
description: > # this means to ignore newlines until "baseurl:"
  Future interplanetary technology breakthroughs and discussions
# social links
twitter_username: # DO NOT include the @ character, or else the build will fail!
github_username:  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
